apiVersion: v2
name: ark-broker
description: Simple in-cluster ephemeral memory for Ark
type: application
version: 0.1.64-rc.1
appVersion: 0.1.64-rc.1
annotations:
  ark.mckinsey.com/service: ark-broker
  ark.mckinsey.com/resources: service
