{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ark-completions
  namespace: {{ .Values.namespace }}
  labels:
    app: ark-completions
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: ark-completions
{{- end }}
