{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ark-completions.serviceAccountName" . }}
  namespace: {{ include "ark-completions.namespace" . }}
  labels:
    app: ark-completions
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
