apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-completions.fullname" . }}
  namespace: {{ include "ark-completions.namespace" . }}
  labels:
    app: ark-completions
spec:
  selector:
    app: ark-completions
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
