apiVersion: v2
name: ark-completions
description: Completions execution engine for Ark queries
type: application
version: 0.1.63-rc.1
appVersion: 0.1.63-rc.1
annotations:
  ark.mckinsey.com/service: completions
  ark.mckinsey.com/resources: service,deployment
