apiVersion: v2
name: ark-completions
description: Completions execution engine for Ark queries
type: application
version: 0.1.66-rc
appVersion: 0.1.66-rc
annotations:
  ark.mckinsey.com/service: completions
  ark.mckinsey.com/resources: service,deployment
