image:
  repository: ghcr.io/mckinsey/agents-at-scale-ark/ark-completions
  tag: ""
  pullPolicy: IfNotPresent

port: 80
targetPort: 9090

serviceAccountName: ark-controller

namespace: ark-system

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi
    ephemeral-storage: 128Mi

securityContext:
  runAsNonRoot: true

customCACert:
  enabled: false
  secretName: "custom-ca-cert"
  key: "ca.crt"

extraVolumes: []
extraVolumeMounts: []
